import type { Product, Category, Banner } from "@/features/products/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "samsung-galaxy-s24-ultra",
    nameAr: "سامسونج جالاكسي S24 الترا",
    nameEn: "Samsung Galaxy S24 Ultra",
    descriptionAr:
      "هاتف ذكي متطور بشاشة 6.8 بوصة Dynamic AMOLED 2X، معالج Snapdragon 8 Gen 3، وكاميرا 200 ميجابكسل مع قلم S Pen المدمج.",
    brand: "Samsung",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1610945264803-c22b62831b7b?w=800&q=80",
      "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&q=80",
    ],
    price: 45000,
    discountedPrice: 38000,
    discountPercent: 16,
    rating: 4.8,
    reviewCount: 1243,
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "2",
    slug: "apple-iphone-15-pro",
    nameAr: "آبل آيفون 15 برو",
    nameEn: "Apple iPhone 15 Pro",
    descriptionAr:
      "أحدث هواتف آبل بتصميم تيتانيوم أنيق، شريحة A17 Pro القوية، وكاميرا احترافية بثلاثة عدسات.",
    brand: "Apple",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80",
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80",
    ],
    price: 52000,
    discountedPrice: 47000,
    discountPercent: 10,
    rating: 4.9,
    reviewCount: 2156,
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "3",
    slug: "sony-wh1000xm5",
    nameAr: "سوني WH-1000XM5 سماعات لاسلكية",
    nameEn: "Sony WH-1000XM5 Wireless Headphones",
    descriptionAr:
      "سماعات رأس لاسلكية بأفضل تقنية إلغاء الضوضاء في العالم، صوت ممتاز وراحة فائقة لساعات طويلة.",
    brand: "Sony",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80",
    ],
    price: 12000,
    discountedPrice: 9500,
    discountPercent: 21,
    rating: 4.7,
    reviewCount: 876,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "4",
    slug: "nike-air-max-270",
    nameAr: "نايكي ماكس 270 حذاء رياضي",
    nameEn: "Nike Air Max 270 Running Shoes",
    descriptionAr:
      "حذاء رياضي بتصميم عصري وتقنية Air Max للراحة القصوى خلال التمارين اليومية.",
    brand: "Nike",
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    price: 3200,
    discountedPrice: 2500,
    discountPercent: 22,
    rating: 4.5,
    reviewCount: 432,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "5",
    slug: "macbook-pro-16-m3",
    nameAr: "ماك بوك برو 16 بوصة بشريحة M3",
    nameEn: "MacBook Pro 16-inch M3",
    descriptionAr:
      "الكمبيوتر المحمول الأكثر قوة من آبل، بشريحة M3 Pro المتطورة وشاشة Liquid Retina XDR.",
    brand: "Apple",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80",
    ],
    price: 89000,
    discountedPrice: 82000,
    discountPercent: 8,
    rating: 4.9,
    reviewCount: 654,
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "6",
    slug: "dyson-v15-detect",
    nameAr: "دايسون V15 مكنسة كهربائية لاسلكية",
    nameEn: "Dyson V15 Detect Cordless Vacuum",
    descriptionAr:
      "مكنسة كهربائية احترافية لاسلكية مع تقنية الكشف بالليزر للغبار الدقيق.",
    brand: "Dyson",
    category: "home",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    price: 18000,
    discountedPrice: 14500,
    discountPercent: 19,
    rating: 4.6,
    reviewCount: 321,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "7",
    slug: "adidas-ultraboost-23",
    nameAr: "أديداس أولترا بوست 23",
    nameEn: "Adidas Ultraboost 23",
    descriptionAr:
      "حذاء الجري الأكثر مبيعاً من أديداس بتقنية Boost الشهيرة لأقصى استرداد للطاقة.",
    brand: "Adidas",
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80",
    ],
    price: 4500,
    discountedPrice: 3600,
    discountPercent: 20,
    rating: 4.4,
    reviewCount: 567,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "8",
    slug: "lg-oled-c3-65",
    nameAr: "LG OLED C3 تلفزيون 65 بوصة",
    nameEn: "LG OLED C3 65-inch TV",
    descriptionAr:
      "تلفزيون OLED مميز بدقة 4K ومعدل تحديث 120Hz مثالي للألعاب والمحتوى السينمائي.",
    brand: "LG",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&q=80",
    ],
    price: 65000,
    discountedPrice: 55000,
    discountPercent: 15,
    rating: 4.8,
    reviewCount: 432,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "9",
    slug: "nescafe-dolce-gusto",
    nameAr: "نسكافيه دولسيه قوستو ماكينة قهوة",
    nameEn: "Nescafe Dolce Gusto Coffee Machine",
    descriptionAr:
      "ماكينة قهوة ذكية بضغط 15 بار لتحضير أشهى المشروبات الساخنة والباردة في المنزل.",
    brand: "Nescafe",
    category: "home",
    images: [
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    ],
    price: 4200,
    discountedPrice: 3200,
    discountPercent: 24,
    rating: 4.3,
    reviewCount: 213,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "10",
    slug: "zara-casual-shirt",
    nameAr: "زارا قميص كاجوال قطني",
    nameEn: "Zara Cotton Casual Shirt",
    descriptionAr:
      "قميص رجالي مريح من القطن عالي الجودة بتصميم كلاسيكي أنيق مناسب لجميع المناسبات.",
    brand: "Zara",
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    ],
    price: 850,
    discountedPrice: 650,
    discountPercent: 24,
    rating: 4.2,
    reviewCount: 145,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "11",
    slug: "instant-pot-duo-7in1",
    nameAr: "إنستنت بوت دو 7 في 1 طنجرة ضغط",
    nameEn: "Instant Pot Duo 7-in-1 Pressure Cooker",
    descriptionAr:
      "طنجرة ضغط كهربائية متعددة الوظائف، توفر وقت الطهي بنسبة 70% مع الحفاظ على القيمة الغذائية.",
    brand: "Instant Pot",
    category: "home",
    images: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    ],
    price: 3500,
    discountedPrice: 2800,
    discountPercent: 20,
    rating: 4.6,
    reviewCount: 789,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "12",
    slug: "xiaomi-robot-vacuum",
    nameAr: "شاومي روبوت تنظيف ذكي",
    nameEn: "Xiaomi Robot Vacuum Cleaner",
    descriptionAr:
      "روبوت تنظيف ذكي بتقنية LDS للرسم الخرائطي وتنظيف شامل بكفاءة عالية يتحكم فيه عبر التطبيق.",
    brand: "Xiaomi",
    category: "home",
    images: [
      "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80",
    ],
    price: 7500,
    discountedPrice: 5900,
    discountPercent: 21,
    rating: 4.4,
    reviewCount: 456,
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "13",
    slug: "polo-ralph-lauren-hoodie",
    nameAr: "بولو رالف لورن هودي قطني",
    nameEn: "Polo Ralph Lauren Cotton Hoodie",
    descriptionAr:
      "هودي كلاسيكي من رالف لورين صنع من قطن عالي الجودة مع شعار البولو المطرز.",
    brand: "Ralph Lauren",
    category: "clothing",
    images: [
      "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&q=80",
    ],
    price: 1800,
    discountedPrice: 1400,
    discountPercent: 22,
    rating: 4.5,
    reviewCount: 231,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "14",
    slug: "canon-eos-r6-mark-ii",
    nameAr: "كانون EOS R6 مارك II كاميرا احترافية",
    nameEn: "Canon EOS R6 Mark II Camera",
    descriptionAr:
      "كاميرا ميرورليس احترافية بدقة 24.2 ميجابكسل، تصوير فيديو 4K 60p، ونظام تثبيت مدمج قوي.",
    brand: "Canon",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
    ],
    price: 54000,
    discountedPrice: 48000,
    discountPercent: 11,
    rating: 4.8,
    reviewCount: 345,
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "15",
    slug: "ikea-bed-frame-leirvik",
    nameAr: "إيكيا إطار سرير ليرفيك",
    nameEn: "IKEA LEIRVIK Bed Frame",
    descriptionAr:
      "إطار سرير بتصميم اسكندنافي كلاسيكي مصنوع من الحديد المطلي بطلاء أبيض ناعم.",
    brand: "IKEA",
    category: "furniture",
    images: [
      "https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800&q=80",
    ],
    price: 4800,
    discountedPrice: 4800,
    discountPercent: 0,
    rating: 4.1,
    reviewCount: 567,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "16",
    slug: "loreal-revitalift-serum",
    nameAr: "لوريال ريفيتاليفت سيروم فيتامين سي",
    nameEn: "L'Oreal Revitalift Vitamin C Serum",
    descriptionAr:
      "سيروم متجدد بتركيزة 12% من فيتامين C الخالص لبشرة مشرقة وشابة مع تقليل التجاعيد.",
    brand: "L'Oreal",
    category: "beauty",
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80",
    ],
    price: 920,
    discountedPrice: 720,
    discountPercent: 22,
    rating: 4.3,
    reviewCount: 1234,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "17",
    slug: "garmin-fenix-7-pro",
    nameAr: "جارمن فينيكس 7 برو ساعة رياضية",
    nameEn: "Garmin Fenix 7 Pro Smartwatch",
    descriptionAr:
      "ساعة رياضية احترافية بنظام GPS متعدد الأقمار الصناعية، مصنوعة من التيتانيوم، ومقاومة للماء.",
    brand: "Garmin",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800&q=80",
    ],
    price: 28000,
    discountedPrice: 23000,
    discountPercent: 18,
    rating: 4.7,
    reviewCount: 432,
    inStock: true,
    isNew: true,
    isFeatured: true,
  },
  {
    id: "18",
    slug: "roborock-s8-pro",
    nameAr: "روبوروك S8 برو أولترا مكنسة روبوت",
    nameEn: "Roborock S8 Pro Ultra Robot Vacuum",
    descriptionAr:
      "روبوت تنظيف وغسيل الأرضيات بتقنية DuoRoller وشحن ذاتي تلقائي في المحطة.",
    brand: "Roborock",
    category: "home",
    images: [
      "https://images.unsplash.com/photo-1652354983329-f359df33a09a?w=800&q=80",
    ],
    price: 14000,
    discountedPrice: 11000,
    discountPercent: 21,
    rating: 4.6,
    reviewCount: 234,
    inStock: false,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "19",
    slug: "pantene-hair-care-set",
    nameAr: "بانتين طقم العناية بالشعر",
    nameEn: "Pantene Hair Care Set",
    descriptionAr:
      "طقم متكامل للعناية بالشعر يشمل شامبو ومكيف وقناع مغذٍ بتركيبة Pro-V المثبتة علمياً.",
    brand: "Pantene",
    category: "beauty",
    images: [
      "https://images.unsplash.com/photo-1607602132700-068979ab6bb1?w=800&q=80",
    ],
    price: 450,
    discountedPrice: 350,
    discountPercent: 22,
    rating: 4.2,
    reviewCount: 678,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "20",
    slug: "playstation-5-slim",
    nameAr: "سوني بلايستيشن 5 سليم",
    nameEn: "Sony PlayStation 5 Slim",
    descriptionAr:
      "أحدث إصدار من بلايستيشن 5 بتصميم أنحف وأخف، سرعة تحميل فائقة وتجربة لعب لا مثيل لها.",
    brand: "Sony",
    category: "electronics",
    images: [
      "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&q=80",
    ],
    price: 20000,
    discountedPrice: 17000,
    discountPercent: 15,
    rating: 4.9,
    reviewCount: 3241,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
];

export const mockCategories: Category[] = [
  {
    id: "1",
    slug: "electronics",
    nameAr: "إلكترونيات",
    nameEn: "Electronics",
    icon: "Smartphone",
    image:
      "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&q=80",
    productCount: 245,
  },
  {
    id: "2",
    slug: "clothing",
    nameAr: "أزياء وملابس",
    nameEn: "Fashion & Clothing",
    icon: "Shirt",
    image:
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400&q=80",
    productCount: 189,
  },
  {
    id: "3",
    slug: "home",
    nameAr: "المنزل والمطبخ",
    nameEn: "Home & Kitchen",
    icon: "Home",
    image:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&q=80",
    productCount: 312,
  },
  {
    id: "4",
    slug: "beauty",
    nameAr: "الجمال والعناية",
    nameEn: "Beauty & Care",
    icon: "Sparkles",
    image:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80",
    productCount: 156,
  },
  {
    id: "5",
    slug: "furniture",
    nameAr: "الأثاث والديكور",
    nameEn: "Furniture & Decor",
    icon: "Sofa",
    image:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
    productCount: 98,
  },
  {
    id: "6",
    slug: "sports",
    nameAr: "رياضة ولياقة",
    nameEn: "Sports & Fitness",
    icon: "Dumbbell",
    image:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80",
    productCount: 134,
  },
  {
    id: "7",
    slug: "books",
    nameAr: "كتب وتعليم",
    nameEn: "Books & Education",
    icon: "BookOpen",
    image:
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80",
    productCount: 423,
  },
  {
    id: "8",
    slug: "toys",
    nameAr: "ألعاب وترفيه",
    nameEn: "Toys & Games",
    icon: "Gamepad2",
    image:
      "https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=400&q=80",
    productCount: 87,
  },
  {
    id: "9",
    slug: "grocery",
    nameAr: "البقالة والأغذية",
    nameEn: "Grocery & Food",
    icon: "ShoppingBasket",
    image:
      "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&q=80",
    productCount: 567,
  },
  {
    id: "10",
    slug: "automotive",
    nameAr: "السيارات والإكسسوارات",
    nameEn: "Automotive & Accessories",
    icon: "Car",
    image:
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&q=80",
    productCount: 73,
  },
];

export const mockBanners: Banner[] = [
  {
    id: "1",
    titleAr: "أقوى تخفيضات الإلكترونيات",
    titleEn: "Biggest Electronics Sale",
    subtitleAr: "خصومات تصل إلى 60% على أحدث الهواتف والأجهزة",
    subtitleEn: "Up to 60% off on the latest phones & devices",
    image:
      "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=1400&q=80",
    ctaTextAr: "تسوق الآن",
    ctaTextEn: "Shop Now",
    ctaLink: "/categories/electronics",
    bgColor: "#0f172a",
  },
  {
    id: "2",
    titleAr: "أزياء الموسم الجديد",
    titleEn: "New Season Fashion",
    subtitleAr: "اكتشف أحدث صيحات الموضة العالمية بأسعار لا تُصدق",
    subtitleEn: "Discover the latest global fashion trends",
    image:
      "https://images.unsplash.com/photo-1445205170230-053b83016050?w=1400&q=80",
    ctaTextAr: "استكشف المجموعة",
    ctaTextEn: "Explore Collection",
    ctaLink: "/categories/clothing",
    bgColor: "#1a0a2e",
  },
  {
    id: "3",
    titleAr: "بيت العمر بأسعار مثالية",
    titleEn: "Home of Your Dreams",
    subtitleAr: "كل ما يحتاجه منزلك من أثاث وأجهزة ومستلزمات",
    subtitleEn: "Everything your home needs at unbeatable prices",
    image:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1400&q=80",
    ctaTextAr: "اكتشف عروضنا",
    ctaTextEn: "Discover Offers",
    ctaLink: "/categories/home",
    bgColor: "#0d1f12",
  },
  {
    id: "4",
    titleAr: "العناية بنفسك تبدأ هنا",
    titleEn: "Self-Care Starts Here",
    subtitleAr: "منتجات جمال وعناية بالبشرة من أفضل الماركات العالمية",
    subtitleEn: "Beauty & skincare from top global brands",
    image:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=1400&q=80",
    ctaTextAr: "تسوقي الآن",
    ctaTextEn: "Shop Now",
    ctaLink: "/categories/beauty",
    bgColor: "#1f0a1a",
  },
];
